@extends('lecturer.app-lecturer')
@section('ketjudul')Aktivitas Pembelajaran@endsection
@section('judul')Tugas & Kuis@endsection
@section('content')
<div class="grid xl:grid-cols-2 gap-6">
<section class="bg-white border border-line rounded-2xl overflow-hidden"><div class="p-5 border-b border-line"><h2 class="font-semibold">Tugas</h2><p class="text-sm text-ink/50 mt-1">Kelola tugas dan koreksi pengumpulan mahasiswa.</p></div><div class="divide-y divide-line">
@forelse($tasks as $task)<div class="p-5"><div class="flex items-start justify-between gap-3"><div><a href="{{ route('lecturer.tugas.show',$task) }}" class="font-medium hover:text-teal">{{ $task->judul }}</a><p class="text-sm text-ink/50 mt-1">{{ $task->pengajaranDosen->kelas->matakuliah->nama_mk ?? '-' }} · Kelas {{ $task->pengajaranDosen->kelas->kode_kelas ?? '-' }}</p></div>@if($task->pending_count)<span class="text-xs rounded-full bg-coral/10 text-coral px-2 py-1">{{ $task->pending_count }} perlu dikoreksi</span>@endif</div><div class="mt-3 flex gap-2"><a class="text-xs px-3 py-1.5 rounded-lg bg-teal text-white" href="{{ route('lecturer.tugas.jawaban.index',$task) }}">Pengumpulan</a><a class="text-xs px-3 py-1.5 rounded-lg border border-line" href="{{ route('lecturer.tugas.edit',$task) }}">Edit</a></div></div>@empty<div class="p-8 text-center text-sm text-ink/45">Belum ada tugas.</div>@endforelse</div><div class="p-4 border-t border-line">{{ $tasks->links() }}</div></section>
<section class="bg-white border border-line rounded-2xl overflow-hidden"><div class="p-5 border-b border-line flex items-center justify-between"><div><h2 class="font-semibold">Kuis</h2><p class="text-sm text-ink/50 mt-1">Kelola soal dan publikasi kuis.</p></div></div><div class="divide-y divide-line">
@forelse($quizzes as $quiz)<div class="p-5"><div class="flex items-start justify-between gap-3"><div><a href="{{ route('lecturer.quiz.show',$quiz) }}" class="font-medium hover:text-teal">{{ $quiz->judul }}</a><p class="text-sm text-ink/50 mt-1">{{ $quiz->pengajaranDosen->kelas->matakuliah->nama_mk ?? '-' }} · {{ $quiz->questions_count }} soal</p></div><span class="text-xs px-2 py-1 rounded-full {{ $quiz->is_published ? 'bg-teal/10 text-teal' : 'bg-ink/5 text-ink/50' }}">{{ $quiz->is_published ? 'Dipublikasi' : 'Draft' }}</span></div><div class="mt-3"><a class="text-xs px-3 py-1.5 rounded-lg border border-line" href="{{ route('lecturer.quiz.show',$quiz) }}">Kelola Kuis</a></div></div>@empty<div class="p-8 text-center text-sm text-ink/45">Belum ada kuis.</div>@endforelse</div></section>
</div>
@endsection
