@php($layout = auth()->user()->role === 'admin' ? 'admin.app-admin' : (auth()->user()->role === 'lecturer' ? 'lecturer.app-lecturer' : 'student.app-student'))
@extends($layout)
@section('ketjudul')Akademik@endsection
@section('judul')Jadwal Kuliah@endsection
@section('content')
<div class="mb-5 p-4 rounded-xl bg-amber/10 border border-amber/20 text-sm text-ink/70">Schema saat ini belum memiliki kolom hari, jam, atau ruang untuk jadwal reguler. Halaman ini menampilkan kelas dan riwayat sesi pertemuan/absensi yang memang tersedia di database, tanpa mengubah migrasi.</div>
<div class="grid xl:grid-cols-2 gap-6"><section class="bg-white border border-line rounded-2xl overflow-hidden"><div class="p-5 border-b border-line"><h2 class="font-semibold">Kelas</h2></div><div class="divide-y divide-line">@forelse($classes as $class)<div class="p-5"><p class="font-medium">{{ $class->matakuliah->nama_mk ?? '-' }}</p><p class="text-sm text-ink/50 mt-1">{{ $class->matakuliah->kode_mk ?? '-' }} · Kelas {{ $class->kode_kelas }}</p><p class="text-xs text-ink/40 mt-2">Pengajar: {{ $class->pengajaranDosen->map(fn($x) => $x->lecturer->user->name ?? '-')->join(', ') ?: '-' }}</p></div>@empty<div class="p-8 text-center text-sm text-ink/45">Belum ada kelas.</div>@endforelse</div></section>
<section class="bg-white border border-line rounded-2xl overflow-hidden"><div class="p-5 border-b border-line"><h2 class="font-semibold">Riwayat Pertemuan</h2></div><div class="divide-y divide-line">@forelse($sessions as $session)<div class="p-5"><div class="flex justify-between gap-3"><div><p class="font-medium">{{ $session->kelas->matakuliah->nama_mk ?? '-' }} · Kelas {{ $session->kelas->kode_kelas ?? '-' }}</p><p class="text-sm text-ink/50 mt-1">{{ $session->judul ?: 'Pertemuan '.$session->pertemuan_ke }}</p></div><span class="text-xs font-mono text-ink/45">{{ optional($session->dibuka_pada)->format('d M Y H:i') }}</span></div></div>@empty<div class="p-8 text-center text-sm text-ink/45">Belum ada sesi pertemuan.</div>@endforelse</div></section></div>
@endsection
